# -*- coding: utf-8 -*-
"""ByLearn3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10_86gTCgdJXKm-a7Z5DfniXOnZHF4in2

# Condicionais

Principal forma de atribuir uma lógica ao seu código.

Basicamente é uma tomada de decisão caso a condição seja verdadeira.

Ex:

- Se o dia estiver quente:
   - Vai tomar um sorvete
   - Vai para a praia

- Do contrario (se não)
  - Comer um chocolate
  - Maratonar
"""

temperatura = 'frio'

print(temperatura)

if temperatura = 'quente':
  print('Vai tomar um sorvete')
  print('Vai para a praia') 
else:
  print('Vai comer um chocolate') 
  print('Vai assistir série')

horario = 'tarde'

if horario == 'manhã':
  print('O sol está quente')
elif horario == 'tarde':
  print('O por do sol esta chegando')
else:
  print('A lua esta linda')
  print('Esta na hora da jornada')

idade = 16

if idade >= 18:
  print('Você ja pode beber')
else:
  print('Você não pode beber')

temperatura = 37

if temperatura <= 30:
  print('Aceitavel')
else:
  print('Socorro, esta muito quente')

altura = 1.72

if altura < 1.80:
  print('Voce é baixinho')
else:
  print('Você é alto')

quente = True
gosta_de_praia = False
Chocolate_Quente = True

if quente == True:
  print('Esta quente')
  if gosta_de_praia == True:
    print('Va para a praia')
  else:
    print('Não va a praia')
else:
  print('Esta frio')
  if Chocolate_Quente == True:
     print('toma um chocolate quente')
  else:
    print('Não tome chocolate quente')

dia = 'domingo'

if dia == 'sabado':
  print('É fim de semana')
elif dia == 'domingo':
  print('É fim de semana')
else

# 1, 3, 6 e 10 => Válido
# qualquer outro => Inválido

numero = 6

if numero == 1:
  print('é valido')
elif numero == 3:
  print('é valido')
elif numero == 6:
  print('é valido')
elif numero == 10:
  print('é valido')
else:
  print('é invalido')

"""# Operadores lógicos

Servem para fazer uma condição composta

E => Ambas precisam ser verdade
Ou => Pelo menos uma precisa ser verdade

Ex
 -Se for de manhã E estiver sol
 -Se for sabado ou domingo

E =>AND
OU => OUR
"""

# 1, 3, 6 e 10 => Válido
# qualquer outro => Inválido

numero = 111

if numero == 1:
  print('é valido')
elif numero == 3:
  print('é valido')
elif numero == 6:
  print('é valido')
elif numero == 10:
  print('é valido')
else:
  print('é invalido')

print('   1     /   2    /     3    /    ')
numero = 3

if numero == 1 or numero == 3 or numero == 6 or numero == 10:
   print('É valido')
else:
   print('É invalido')

horario = 'manha'
sol = True

if horario == 'manha' and sol == True:
  print('Esta ensolarado')

Meu_nome = 'Joao'
nome = input('Digite seu nome: ')

Meu_Sobrenome = 'Gabriel'
sobrenome = input('Digite seu sobrenome: ')

if nome == Meu_nome and sobrenome == Meu_Sobrenome:
  print('Você é o Joao Gabriel')
else:
  print('Você não é o Joao Gabriel')

"""# Laços de repetição

É uma forma de evitar repetição de código

Ele vai "executar n vezes" uma operação".

n => quantidade de vezes definida.
"""

# De 1 até 10 vamos printar todos os numeros
print(1)
print(2)
print(3)
print(4)
print(5)
print(6)
print(7)
print(8)
print(9)
print(10)
# Na programação o minimo (1) é INCLUSIVO => Ele existe
# Ja o maximo (10) é EXCLUSIVO => Ele não existe

for numero in range(1,10):
 print(numero)

"""For => Nossa palavra chave para repetiçãp.

Variavel => O dado que estamos trabalhando no momento atual.

In => Nossa palavra chave para "onde vamos repetir?"

Intervalo/sequencia => O que vamos repetir
"""

for numero in range(5):
  print(numero)


#    for      numero      in    range(5)
# para cada   numero      no    intervalo até 5

for numero in range(1, 11):
  print('O numero atual é:', numero)

for numero in range(1, 11):
  print('O numero atual é:', numero)
  if numero == 5:
    print('é o numero 5')
  if numero == 2:
    print('é o numero 2')
  if numero == 3:
    print('é o numero 3')

texto = 'Não trava o zap dos amigos'
 
for vez in range(20):
  print(vez, texto)

nomes = ['Joao', 'juliana','silvana']

for nome in nomes:
  print('O nome atual é', nome)
  if nome == 'Joao':
    print('(Ou zarcky)')

notas = [6, 7.5, 9, 10, 3, 5]

soma = 0

for nota in notas:
  soma = soma + nota

print('A soma é', soma)

media = soma / len(notas)

print('A média é', media)

# len => Tamanho em ingles
    # 1 2
notas = [6, 7.5]
len(notas)

# range = intervalo em ingles
# range(1, 10) => intervalo de 1 até 10

lista1 = ['A', 'B', 'C']
lista2 = [1, 2, 3, 4, 5]

tam_lista1 = len(lista1)
tam_lista2 = len(lista2)

print(tam_lista1)
print(tam_lista2)

"""# Função

Toda função é uma rotina

Eu defino (def) uma rotina e a executo quantas vezes quiser.

é uma excelente forma de deixar o codigo dinamico e sem repetição.
"""

# Definindo a função
def nome_funcao():
  # Código da funcao
  print('codigo da função')

# Chamando a função
nome_funcao()

def mostrar_nome():
  print('Joao gabriel')
  print('gabriel')
  
mostrar_nome()
mostrar_nome()

"""## Parâmetro/argumento da função

é uma maneira de enviar dados para a função
"""

def mostrar_nome(nome_atual):
  print(nome_atual)

mostrar_nome('Jão1')
mostrar_nome('jão2')
mostrar_nome('jão3')

def calcular_media(nota1, nota2):
  soma = nota1 + nota2
  media = soma / 2
  print(media)

primeira_nota = float(input('sua primeira nota: '))
segunda_nota = float(input('sua segunda nota: '))

calcular_media(primeira_nota, segunda_nota)